#!/usr/bin/env python3
"""Detect large irradiance irregularity windows, especially mapping-related breaks."""

from __future__ import annotations

import argparse
from bisect import bisect_right
from dataclasses import dataclass
from pathlib import Path

import matplotlib.dates as mdates
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

try:
    from stw_pipeline_common import COLUMN_MAP_WORKBOOK, load_column_map_workbook
    from pipeline_config import load_config
except ModuleNotFoundError:  # pragma: no cover - supports imports from repo root/notebooks.
    from scripts.stw_pipeline_common import COLUMN_MAP_WORKBOOK, load_column_map_workbook
    from scripts.pipeline_config import load_config


SCRIPT_DIR = Path(__file__).resolve().parent
ROOT_DIR = SCRIPT_DIR.parent
_CONFIG = load_config()
DEFAULT_PARQUET_INPUT = _CONFIG.mv_irr_parquet
DEFAULT_EVENTS_OUTPUT = _CONFIG.irr_irregularity_events_file
DEFAULT_PLOT_INDEX_OUTPUT = _CONFIG.irr_irregularity_plot_index_file
DEFAULT_PLOTS_DIR = _CONFIG.irr_irregularity_plots_dir

# Default mode: focus on large, sustained windows that suggest a bad column map.
DEFAULT_MODE = "mapping_window"

# Mapping-window detector defaults.
DEFAULT_DAYLIGHT_MIN_IRR = 50.0
DEFAULT_PHYSICAL_MAX_IRR = 3000.0
DEFAULT_SEGMENT_CLOSURE_BREAK_THRESHOLD = 0.35
DEFAULT_SEGMENT_CLOSURE_COLLAPSE_THRESHOLD = 0.85
DEFAULT_DAILY_MERGE_GAP_DAYS = 1
DEFAULT_DAILY_MIN_EVENT_DAYS = 2
DEFAULT_SINGLE_DAY_SEVERE_SCORE = 6.0
DEFAULT_PLOT_CONTEXT_DAYS = 45
MIN_CLOSURE_POINTS = 60
MAPPING_CHANGE_NEARBY_DAYS = 3

# Legacy first-difference detector defaults.
DEFAULT_CHANGE_QUANTILE = 0.99995
DEFAULT_LOCAL_Z_THRESHOLD = 6.0
DEFAULT_ROLLING_WINDOW = 241
DEFAULT_MERGE_GAP_MINUTES = 45
DEFAULT_MIN_FLAGGED_POINTS = 2
DEFAULT_PLOT_CONTEXT_HOURS = 6
ROLLING_MIN_PERIODS = 41

METRICS = ("GHI", "DNI", "DHI")
IRR_COLUMNS = [f"{metric}_Irr" for metric in METRICS]
METRIC_CONFIG = {
    "GHI": {"color": "#1f77b4", "min_abs_delta": 200.0},
    "DNI": {"color": "#ff7f0e", "min_abs_delta": 250.0},
    "DHI": {"color": "#2ca02c", "min_abs_delta": 80.0},
}


@dataclass(frozen=True)
class EventDetectionArtifacts:
    """Artifacts generated by one irregularity detection run."""

    events_output: Path
    events_written: int


def parse_args() -> argparse.Namespace:
    """Parse CLI arguments."""
    parser = argparse.ArgumentParser(
        description=(
            "Detect large irradiance irregularity events. The default mode focuses on sustained "
            "mapping-related breaks; the legacy first-difference detector is still available."
        )
    )
    parser.add_argument(
        "--input-parquet",
        type=Path,
        default=DEFAULT_PARQUET_INPUT,
        help=f"Path to the cleaned mV/Irr parquet file (default: {DEFAULT_PARQUET_INPUT})",
    )
    parser.add_argument(
        "--events-output",
        type=Path,
        default=DEFAULT_EVENTS_OUTPUT,
        help=f"Path to the irregularity events CSV (default: {DEFAULT_EVENTS_OUTPUT})",
    )
    parser.add_argument(
        "--mode",
        choices=("mapping_window", "first_difference"),
        default=DEFAULT_MODE,
        help=(
            "Detection mode. 'mapping_window' looks for sustained balance/mapping breaks; "
            "'first_difference' keeps the older minute-to-minute spike detector."
        ),
    )
    parser.add_argument(
        "--workbook",
        type=Path,
        default=COLUMN_MAP_WORKBOOK,
        help=f"Workbook used to annotate mapping periods (default: {COLUMN_MAP_WORKBOOK})",
    )
    parser.add_argument(
        "--daylight-min-irr",
        type=float,
        default=DEFAULT_DAYLIGHT_MIN_IRR,
        help=f"Minimum irradiance used to treat a row as daytime for daily summaries (default: {DEFAULT_DAYLIGHT_MIN_IRR})",
    )
    parser.add_argument(
        "--physical-max-irr",
        type=float,
        default=DEFAULT_PHYSICAL_MAX_IRR,
        help=f"Hard upper limit used to flag obviously impossible irradiance (default: {DEFAULT_PHYSICAL_MAX_IRR})",
    )
    parser.add_argument(
        "--segment-closure-break-threshold",
        type=float,
        default=DEFAULT_SEGMENT_CLOSURE_BREAK_THRESHOLD,
        help=(
            "Minimum median daily solar-closure error for a mapping segment to be considered broken "
            f"(default: {DEFAULT_SEGMENT_CLOSURE_BREAK_THRESHOLD})"
        ),
    )
    parser.add_argument(
        "--segment-closure-collapse-threshold",
        type=float,
        default=DEFAULT_SEGMENT_CLOSURE_COLLAPSE_THRESHOLD,
        help=(
            "Minimum median daily solar-closure error for a mapping segment to be considered collapsed "
            f"(default: {DEFAULT_SEGMENT_CLOSURE_COLLAPSE_THRESHOLD})"
        ),
    )
    parser.add_argument(
        "--daily-merge-gap-days",
        type=int,
        default=DEFAULT_DAILY_MERGE_GAP_DAYS,
        help=(
            "For severe daily anomalies outside abnormal mapping segments, merge nearby flagged dates "
            f"when separated by at most this many days (default: {DEFAULT_DAILY_MERGE_GAP_DAYS})"
        ),
    )
    parser.add_argument(
        "--daily-min-event-days",
        type=int,
        default=DEFAULT_DAILY_MIN_EVENT_DAYS,
        help=(
            "Minimum flagged days required to keep a daily-severe event unless the event is extreme "
            f"(default: {DEFAULT_DAILY_MIN_EVENT_DAYS})"
        ),
    )
    parser.add_argument(
        "--single-day-severe-score",
        type=float,
        default=DEFAULT_SINGLE_DAY_SEVERE_SCORE,
        help=(
            "Keep a single-day daily event when its severity score is at least this large "
            f"(default: {DEFAULT_SINGLE_DAY_SEVERE_SCORE})"
        ),
    )
    parser.add_argument(
        "--plot-context-days",
        type=float,
        default=DEFAULT_PLOT_CONTEXT_DAYS,
        help=f"Days of context to recommend before and after mapping-window plots (default: {DEFAULT_PLOT_CONTEXT_DAYS})",
    )

    # Legacy first-difference detector knobs.
    parser.add_argument(
        "--change-quantile",
        type=float,
        default=DEFAULT_CHANGE_QUANTILE,
        help=f"Quantile used for the absolute first-difference threshold (default: {DEFAULT_CHANGE_QUANTILE})",
    )
    parser.add_argument(
        "--local-z-threshold",
        type=float,
        default=DEFAULT_LOCAL_Z_THRESHOLD,
        help=f"Local robust z-score threshold on first differences (default: {DEFAULT_LOCAL_Z_THRESHOLD})",
    )
    parser.add_argument(
        "--rolling-window",
        type=int,
        default=DEFAULT_ROLLING_WINDOW,
        help=f"Centered rolling window for local median/MAD on first differences (default: {DEFAULT_ROLLING_WINDOW})",
    )
    parser.add_argument(
        "--merge-gap-minutes",
        type=int,
        default=DEFAULT_MERGE_GAP_MINUTES,
        help=(
            "Legacy mode only: merge flagged timestamps into one event when separated by at most "
            f"this many minutes (default: {DEFAULT_MERGE_GAP_MINUTES})"
        ),
    )
    parser.add_argument(
        "--min-flagged-points",
        type=int,
        default=DEFAULT_MIN_FLAGGED_POINTS,
        help=(
            "Legacy mode only: minimum flagged timestamps required to keep an event "
            f"(default: {DEFAULT_MIN_FLAGGED_POINTS})"
        ),
    )
    parser.add_argument(
        "--plot-context-hours",
        type=float,
        default=DEFAULT_PLOT_CONTEXT_HOURS,
        help=f"Legacy mode only: hours of context before and after each event plot (default: {DEFAULT_PLOT_CONTEXT_HOURS})",
    )
    return parser.parse_args()


def load_metric_frame(parquet_path: Path, metric: str) -> pd.DataFrame:
    """Load one cleaned IRR metric from parquet."""
    irr_column = f"{metric}_Irr"
    frame = pd.read_parquet(parquet_path, columns=["datetime", irr_column]).copy()
    frame["datetime"] = pd.to_datetime(frame["datetime"], errors="coerce")
    frame[irr_column] = pd.to_numeric(frame[irr_column], errors="coerce")
    frame = frame.dropna(subset=["datetime"]).sort_values("datetime").reset_index(drop=True)
    if frame.empty:
        raise ValueError(f"No rows found for {metric} in {parquet_path}.")
    return frame


def load_irr_frame(parquet_path: Path) -> pd.DataFrame:
    """Load the irradiance columns needed for mapping-window detection."""
    frame = pd.read_parquet(parquet_path, columns=["datetime", *IRR_COLUMNS, "SZA"]).copy()
    frame["datetime"] = pd.to_datetime(frame["datetime"], errors="coerce")
    for column in [*IRR_COLUMNS, "SZA"]:
        frame[column] = pd.to_numeric(frame[column], errors="coerce")
    frame = frame.dropna(subset=["datetime"]).sort_values("datetime").reset_index(drop=True)
    if frame.empty:
        raise ValueError(f"No rows found in {parquet_path}.")
    return frame


def build_daily_summary(irr_frame: pd.DataFrame, daylight_min_irr: float) -> pd.DataFrame:
    """Aggregate the minute-level irradiance frame into day-level features."""
    daytime_mask = irr_frame[IRR_COLUMNS].fillna(0).max(axis=1).ge(daylight_min_irr)
    daylight = irr_frame.loc[daytime_mask, ["datetime", *IRR_COLUMNS, "SZA"]].copy()
    if daylight.empty:
        raise ValueError("No daytime irradiance rows were available to summarize.")

    daylight["date"] = daylight["datetime"].dt.normalize()
    daily = pd.DataFrame(index=pd.Index(sorted(daylight["date"].unique()), name="date"))

    grouped = daylight.groupby("date")
    for metric in METRICS:
        prefix = metric.lower()
        metric_group = grouped[f"{metric}_Irr"]
        daily[f"{prefix}_count"] = metric_group.count()
        daily[f"{prefix}_p95"] = metric_group.quantile(0.95)
        daily[f"{prefix}_max"] = metric_group.max()

    closure_mask = (
        daylight["SZA"].between(0, 89.5)
        & daylight[IRR_COLUMNS].notna().all(axis=1)
    )
    closure_frame = daylight.loc[closure_mask, ["date", *IRR_COLUMNS, "SZA"]].copy()
    if not closure_frame.empty:
        cos_zenith = np.cos(np.deg2rad(closure_frame["SZA"]))
        closure_component = closure_frame["DNI_Irr"] * cos_zenith + closure_frame["DHI_Irr"]
        closure_frame["closure_rel_err"] = (
            (closure_frame["GHI_Irr"] - closure_component).abs()
            / pd.concat([closure_frame["GHI_Irr"], closure_component], axis=1).max(axis=1).clip(lower=1.0)
        )
        closure_group = closure_frame.groupby("date")["closure_rel_err"]
        daily["closure_p95"] = closure_group.quantile(0.95)
        daily["closure_median"] = closure_group.median()
        daily["closure_count"] = closure_group.count()
    else:
        daily["closure_p95"] = np.nan
        daily["closure_median"] = np.nan
        daily["closure_count"] = 0

    daily["dni_to_ghi_p95"] = daily["dni_p95"] / daily["ghi_p95"].clip(lower=1.0)
    daily["dhi_to_ghi_p95"] = daily["dhi_p95"] / daily["ghi_p95"].clip(lower=1.0)
    daily["peak_irr_max"] = daily[[f"{metric.lower()}_max" for metric in METRICS]].max(axis=1, skipna=True)
    return daily.sort_index()


def build_mapping_periods(workbook_path: Path) -> list[dict[str, pd.Timestamp | None]]:
    """Return workbook mapping periods annotated with exact effective timestamps."""
    _, snapshots, _ = load_column_map_workbook(workbook_path)
    periods: list[dict[str, pd.Timestamp | None]] = []
    for index, snapshot in enumerate(snapshots):
        next_effective = (
            pd.Timestamp(snapshots[index + 1].effective_at)
            if index + 1 < len(snapshots)
            else None
        )
        periods.append(
            {
                "effective_at": pd.Timestamp(snapshot.effective_at),
                "start_date": pd.Timestamp(snapshot.effective_at).normalize(),
                "next_effective_at": next_effective,
                "end_date": (
                    next_effective.normalize() - pd.Timedelta(days=1)
                    if next_effective is not None
                    else None
                ),
            }
        )
    return periods


def mapping_period_for_date(
    periods: list[dict[str, pd.Timestamp | None]],
    date_value: pd.Timestamp,
) -> dict[str, pd.Timestamp | None] | None:
    """Return the workbook mapping period containing *date_value*."""
    if not periods:
        return None
    starts = [period["start_date"] for period in periods]
    period_index = bisect_right(starts, date_value.normalize()) - 1
    if period_index < 0:
        return None
    return periods[period_index]


def nearest_mapping_change(
    periods: list[dict[str, pd.Timestamp | None]],
    date_value: pd.Timestamp,
) -> pd.Timestamp | pd.NaT:
    """Return the closest workbook effective timestamp to *date_value*."""
    if not periods:
        return pd.NaT
    return min(
        (period["effective_at"] for period in periods),
        key=lambda effective_at: abs(effective_at - date_value),
    )


def _add_rule(
    rule_records: list[tuple[str, float]],
    rule_name: str,
    severity: float,
    affected_metrics: set[str],
    metrics_to_add: list[str],
) -> None:
    """Append one triggered rule and track the metrics it implicates."""
    rule_records.append((rule_name, float(severity)))
    affected_metrics.update(metrics_to_add)


def evaluate_daily_structural_flags(
    daily: pd.DataFrame,
    physical_max_irr: float,
    segment_closure_break_threshold: float,
    segment_closure_collapse_threshold: float,
) -> pd.DataFrame:
    """Evaluate day-level structural rules aimed at mapping mistakes."""
    records: list[dict[str, object]] = []

    for date_value, row in daily.iterrows():
        rule_records: list[tuple[str, float]] = []
        affected_metrics: set[str] = set()
        closure_available = bool(row.get("closure_count", 0) >= MIN_CLOSURE_POINTS and pd.notna(row.get("closure_p95")))

        max_metrics = [
            metric
            for metric in METRICS
            if pd.notna(row.get(f"{metric.lower()}_max")) and row[f"{metric.lower()}_max"] > physical_max_irr
        ]
        if max_metrics:
            severity = 8.0 + max(0.0, (float(row["peak_irr_max"]) - physical_max_irr) / 1000.0)
            _add_rule(rule_records, "irr_above_physical_limit", severity, affected_metrics, max_metrics)

        if closure_available and float(row["closure_p95"]) >= segment_closure_collapse_threshold:
            severity = 7.0 + (float(row["closure_p95"]) - segment_closure_collapse_threshold) * 10.0
            _add_rule(
                rule_records,
                "solar_closure_collapsed",
                severity,
                affected_metrics,
                list(METRICS),
            )

        if (
            closure_available
            and float(row["closure_p95"]) >= segment_closure_break_threshold
            and pd.notna(row.get("dni_p95"))
            and pd.notna(row.get("ghi_p95"))
            and float(row["dni_p95"]) >= 600.0
            and float(row["ghi_p95"]) <= 600.0
            and float(row["dni_to_ghi_p95"]) >= 1.45
        ):
            severity = 4.0 + (float(row["dni_to_ghi_p95"]) - 1.45) * 3.0
            _add_rule(
                rule_records,
                "ghi_suppressed_relative_to_dni",
                severity,
                affected_metrics,
                ["GHI", "DNI", "DHI"],
            )

        if (
            pd.notna(row.get("ghi_p95"))
            and pd.notna(row.get("dni_p95"))
            and pd.notna(row.get("dhi_p95"))
            and float(row["ghi_p95"]) >= 600.0
            and float(row["dni_p95"]) <= 25.0
            and float(row["dhi_p95"]) <= 25.0
            and float(row.get("dhi_count", 0)) >= MIN_CLOSURE_POINTS
        ):
            severity = 6.0 + (float(row["ghi_p95"]) - 600.0) / 250.0
            _add_rule(
                rule_records,
                "dni_dhi_flatline_during_high_ghi",
                severity,
                affected_metrics,
                ["DNI", "DHI", "GHI"],
            )

        if (
            closure_available
            and float(row["closure_p95"]) >= segment_closure_break_threshold
            and pd.notna(row.get("dhi_p95"))
            and pd.notna(row.get("ghi_p95"))
            and pd.notna(row.get("dni_p95"))
            and float(row["dhi_p95"]) >= max(float(row["ghi_p95"]) * 1.2, 600.0)
            and float(row["dni_p95"]) <= 100.0
        ):
            severity = 5.0 + max(0.0, float(row["dhi_to_ghi_p95"]) - 1.2) * 3.0
            _add_rule(
                rule_records,
                "dhi_dominates_global_balance",
                severity,
                affected_metrics,
                ["DHI", "GHI", "DNI"],
            )

        sorted_rules = [name for name, _ in sorted(rule_records, key=lambda item: (-item[1], item[0]))]
        score = float(sum(severity for _, severity in rule_records))
        records.append(
            {
                "date": date_value,
                "is_flagged": bool(rule_records),
                "score": score,
                "rule_count": len(rule_records),
                "primary_rule": sorted_rules[0] if sorted_rules else "",
                "rules": sorted_rules,
                "affected_metrics": sorted(affected_metrics),
            }
        )

    return pd.DataFrame(records).set_index("date").sort_index()


def build_event_record(
    event_start_date: pd.Timestamp,
    event_end_date: pd.Timestamp,
    daily: pd.DataFrame,
    daily_flags: pd.DataFrame,
    periods: list[dict[str, pd.Timestamp | None]],
    plot_context_days: float,
    source: str,
    override_rule: str | None = None,
    override_rules: list[str] | None = None,
    override_metrics: list[str] | None = None,
) -> dict[str, object]:
    """Build one event record covering a range of whole days."""
    window = daily.loc[event_start_date:event_end_date].copy()
    flag_window = daily_flags.loc[event_start_date:event_end_date].copy()
    if window.empty:
        raise ValueError("Cannot build an event record from an empty day window.")

    if not flag_window.empty and flag_window["score"].max() > 0:
        peak_date = pd.Timestamp(flag_window["score"].idxmax())
    else:
        peak_date = pd.Timestamp(window["peak_irr_max"].idxmax())

    peak_row = window.loc[peak_date]
    peak_flag = flag_window.loc[peak_date] if peak_date in flag_window.index else None

    all_rules = override_rules or sorted(
        {
            rule_name
            for rules in flag_window.get("rules", pd.Series(dtype=object))
            for rule_name in (rules or [])
        }
    )
    all_metrics = override_metrics or sorted(
        {
            metric
            for metrics in flag_window.get("affected_metrics", pd.Series(dtype=object))
            for metric in (metrics or [])
        }
    )
    primary_rule = override_rule or (
        str(peak_flag["primary_rule"])
        if peak_flag is not None and str(peak_flag["primary_rule"])
        else (all_rules[0] if all_rules else "mapping_window")
    )
    metric = all_metrics[0] if len(all_metrics) == 1 else "MULTI"

    mapping_period = mapping_period_for_date(periods, event_start_date)
    mapping_period_start = mapping_period["effective_at"] if mapping_period else pd.NaT
    mapping_period_end = mapping_period["next_effective_at"] if mapping_period else pd.NaT
    nearest_change = nearest_mapping_change(periods, event_start_date)

    plot_context = pd.Timedelta(days=float(plot_context_days))
    event_end_timestamp = event_end_date + pd.Timedelta(hours=23, minutes=59)
    duration_days = int((event_end_date - event_start_date).days) + 1
    flagged_days = int(flag_window["is_flagged"].sum()) if "is_flagged" in flag_window else 0

    return {
        "metric": metric,
        "affected_metrics": ",".join(all_metrics),
        "source": source,
        "event_start": event_start_date,
        "event_end": event_end_timestamp,
        "duration_days": duration_days,
        "duration_minutes": duration_days * 1440,
        "flagged_days": flagged_days,
        "peak_datetime": peak_date + pd.Timedelta(hours=12),
        "peak_score": float(peak_flag["score"]) if peak_flag is not None else float("nan"),
        "peak_rule_count": int(peak_flag["rule_count"]) if peak_flag is not None else 0,
        "peak_ghi_p95": float(peak_row["ghi_p95"]) if pd.notna(peak_row["ghi_p95"]) else float("nan"),
        "peak_dni_p95": float(peak_row["dni_p95"]) if pd.notna(peak_row["dni_p95"]) else float("nan"),
        "peak_dhi_p95": float(peak_row["dhi_p95"]) if pd.notna(peak_row["dhi_p95"]) else float("nan"),
        "peak_ghi_max": float(peak_row["ghi_max"]) if pd.notna(peak_row["ghi_max"]) else float("nan"),
        "peak_dni_max": float(peak_row["dni_max"]) if pd.notna(peak_row["dni_max"]) else float("nan"),
        "peak_dhi_max": float(peak_row["dhi_max"]) if pd.notna(peak_row["dhi_max"]) else float("nan"),
        "peak_closure_p95": float(peak_row["closure_p95"]) if pd.notna(peak_row["closure_p95"]) else float("nan"),
        "window_ghi_p95_median": float(window["ghi_p95"].median(skipna=True)) if not window.empty else float("nan"),
        "window_dni_p95_median": float(window["dni_p95"].median(skipna=True)) if not window.empty else float("nan"),
        "window_dhi_p95_median": float(window["dhi_p95"].median(skipna=True)) if not window.empty else float("nan"),
        "window_dni_to_ghi_median": float(window["dni_to_ghi_p95"].median(skipna=True)) if not window.empty else float("nan"),
        "window_dhi_to_ghi_median": float(window["dhi_to_ghi_p95"].median(skipna=True)) if not window.empty else float("nan"),
        "window_closure_p95_median": float(window["closure_p95"].median(skipna=True)) if not window.empty else float("nan"),
        "rule": primary_rule,
        "rules": ",".join(all_rules),
        "mapping_period_start": mapping_period_start,
        "mapping_period_end": mapping_period_end,
        "starts_near_mapping_change": bool(
            pd.notna(nearest_change)
            and abs(event_start_date - nearest_change.normalize()) <= pd.Timedelta(days=MAPPING_CHANGE_NEARBY_DAYS)
        ),
        "nearest_mapping_change": nearest_change,
        "plot_context_days": float(plot_context_days),
        "plot_start": event_start_date - plot_context,
        "plot_end": event_end_timestamp + plot_context,
    }


def detect_mapping_segment_events(
    daily: pd.DataFrame,
    daily_flags: pd.DataFrame,
    workbook_path: Path,
    segment_closure_break_threshold: float,
    segment_closure_collapse_threshold: float,
    plot_context_days: float,
) -> tuple[list[dict[str, object]], list[tuple[pd.Timestamp, pd.Timestamp]], list[dict[str, pd.Timestamp | None]]]:
    """Detect long abnormal windows aligned with workbook mapping periods."""
    periods = build_mapping_periods(workbook_path)
    events: list[dict[str, object]] = []
    occupied_ranges: list[tuple[pd.Timestamp, pd.Timestamp]] = []

    for period in periods:
        start_date = pd.Timestamp(period["start_date"])
        end_date = pd.Timestamp(period["end_date"]) if period["end_date"] is not None else daily.index.max()
        segment = daily.loc[start_date:end_date]
        if segment.empty:
            continue

        closure_segment = segment.loc[segment["closure_count"].fillna(0) >= MIN_CLOSURE_POINTS]
        if closure_segment.empty:
            continue

        median_ghi_p95 = float(segment["ghi_p95"].median(skipna=True))
        median_dni_p95 = float(segment["dni_p95"].median(skipna=True))
        median_dhi_p95 = float(segment["dhi_p95"].median(skipna=True))
        median_dni_to_ghi = float(segment["dni_to_ghi_p95"].median(skipna=True))
        median_closure_p95 = float(closure_segment["closure_p95"].median(skipna=True))

        rule_name: str | None = None
        rule_list: list[str] = []
        metrics: list[str] = []

        if (
            median_closure_p95 >= segment_closure_collapse_threshold
            and median_ghi_p95 >= 200.0
            and median_dni_p95 <= 25.0
            and median_dhi_p95 <= 25.0
        ):
            rule_name = "mapping_segment_secondary_channels_flatline"
            rule_list = ["solar_closure_collapsed", "dni_dhi_flatline_during_high_ghi"]
            metrics = ["GHI", "DNI", "DHI"]
        elif (
            median_closure_p95 >= segment_closure_break_threshold
            and median_dni_to_ghi >= 1.45
            and median_dni_p95 >= 600.0
            and median_ghi_p95 <= 600.0
        ):
            rule_name = "mapping_segment_ghi_suppressed"
            rule_list = ["ghi_suppressed_relative_to_dni"]
            metrics = ["GHI", "DNI", "DHI"]

        if not rule_name:
            continue

        events.append(
            build_event_record(
                start_date,
                end_date,
                daily,
                daily_flags,
                periods,
                plot_context_days,
                source="mapping_segment",
                override_rule=rule_name,
                override_rules=rule_list,
                override_metrics=metrics,
            )
        )
        occupied_ranges.append((start_date, end_date))

    return events, occupied_ranges, periods


def date_is_occupied(
    date_value: pd.Timestamp,
    occupied_ranges: list[tuple[pd.Timestamp, pd.Timestamp]],
) -> bool:
    """Return True when *date_value* falls inside an already-kept event window."""
    return any(start_date <= date_value <= end_date for start_date, end_date in occupied_ranges)


def detect_daily_severe_events(
    daily: pd.DataFrame,
    daily_flags: pd.DataFrame,
    periods: list[dict[str, pd.Timestamp | None]],
    occupied_ranges: list[tuple[pd.Timestamp, pd.Timestamp]],
    daily_merge_gap_days: int,
    daily_min_event_days: int,
    single_day_severe_score: float,
    plot_context_days: float,
) -> list[dict[str, object]]:
    """Detect severe one-off windows outside the abnormal mapping segments."""
    severe_rule_names = {
        "irr_above_physical_limit",
        "solar_closure_collapsed",
        "dhi_dominates_global_balance",
        "dni_dhi_flatline_during_high_ghi",
    }

    eligible = daily_flags[
        daily_flags["rules"].apply(lambda rules: any(rule_name in severe_rule_names for rule_name in (rules or [])))
    ].copy()
    if eligible.empty:
        return []

    eligible = eligible.loc[~eligible.index.to_series().apply(lambda date_value: date_is_occupied(date_value, occupied_ranges))]
    if eligible.empty:
        return []

    severe_dates = list(eligible.index.sort_values())
    groups: list[tuple[pd.Timestamp, pd.Timestamp]] = []
    start_date = previous_date = severe_dates[0]
    for date_value in severe_dates[1:]:
        if (date_value - previous_date).days <= daily_merge_gap_days:
            previous_date = date_value
            continue
        groups.append((start_date, previous_date))
        start_date = previous_date = date_value
    groups.append((start_date, previous_date))

    events: list[dict[str, object]] = []
    for start_date, end_date in groups:
        flag_window = daily_flags.loc[start_date:end_date]
        duration_days = int((end_date - start_date).days) + 1
        keep_event = duration_days >= daily_min_event_days or float(flag_window["score"].max()) >= single_day_severe_score
        if not keep_event:
            continue

        events.append(
            build_event_record(
                start_date,
                end_date,
                daily,
                daily_flags,
                periods,
                plot_context_days,
                source="daily_severe",
            )
        )

    return events


def detect_mapping_window_events(
    parquet_path: Path,
    workbook_path: Path = COLUMN_MAP_WORKBOOK,
    daylight_min_irr: float = DEFAULT_DAYLIGHT_MIN_IRR,
    physical_max_irr: float = DEFAULT_PHYSICAL_MAX_IRR,
    segment_closure_break_threshold: float = DEFAULT_SEGMENT_CLOSURE_BREAK_THRESHOLD,
    segment_closure_collapse_threshold: float = DEFAULT_SEGMENT_CLOSURE_COLLAPSE_THRESHOLD,
    daily_merge_gap_days: int = DEFAULT_DAILY_MERGE_GAP_DAYS,
    daily_min_event_days: int = DEFAULT_DAILY_MIN_EVENT_DAYS,
    single_day_severe_score: float = DEFAULT_SINGLE_DAY_SEVERE_SCORE,
    plot_context_days: float = DEFAULT_PLOT_CONTEXT_DAYS,
) -> pd.DataFrame:
    """Detect large, sustained mapping-related irradiance windows."""
    irr_frame = load_irr_frame(parquet_path)
    daily = build_daily_summary(irr_frame, daylight_min_irr)
    daily_flags = evaluate_daily_structural_flags(
        daily,
        physical_max_irr,
        segment_closure_break_threshold,
        segment_closure_collapse_threshold,
    )

    segment_events, occupied_ranges, periods = detect_mapping_segment_events(
        daily,
        daily_flags,
        workbook_path,
        segment_closure_break_threshold,
        segment_closure_collapse_threshold,
        plot_context_days,
    )
    daily_events = detect_daily_severe_events(
        daily,
        daily_flags,
        periods,
        occupied_ranges,
        daily_merge_gap_days,
        daily_min_event_days,
        single_day_severe_score,
        plot_context_days,
    )

    events = pd.DataFrame(segment_events + daily_events)
    if events.empty:
        return events

    events = events.sort_values(["event_start", "source", "rule"]).reset_index(drop=True)
    events["event_id"] = [
        f"irr_window_{index:03d}"
        for index in range(1, len(events) + 1)
    ]
    events["plot_label"] = events["event_id"]

    ordered_columns = [
        "event_id",
        "plot_label",
        "metric",
        "affected_metrics",
        "source",
        "event_start",
        "event_end",
        "duration_days",
        "duration_minutes",
        "flagged_days",
        "peak_datetime",
        "peak_score",
        "peak_rule_count",
        "peak_ghi_p95",
        "peak_dni_p95",
        "peak_dhi_p95",
        "peak_ghi_max",
        "peak_dni_max",
        "peak_dhi_max",
        "peak_closure_p95",
        "window_ghi_p95_median",
        "window_dni_p95_median",
        "window_dhi_p95_median",
        "window_dni_to_ghi_median",
        "window_dhi_to_ghi_median",
        "window_closure_p95_median",
        "rule",
        "rules",
        "mapping_period_start",
        "mapping_period_end",
        "starts_near_mapping_change",
        "nearest_mapping_change",
        "plot_context_days",
        "plot_start",
        "plot_end",
    ]
    return events[ordered_columns]


def detect_metric_flagged_points(
    metric_frame: pd.DataFrame,
    metric: str,
    change_quantile: float,
    local_z_threshold: float,
    rolling_window: int,
) -> tuple[pd.DataFrame, float]:
    """Return flagged timestamps for one metric based on extreme first differences."""
    irr_column = f"{metric}_Irr"
    values = pd.to_numeric(metric_frame[irr_column], errors="coerce")
    previous_values = values.shift(1)
    signed_delta = values - previous_values
    abs_delta = signed_delta.abs()

    local_median = abs_delta.rolling(
        window=rolling_window,
        center=True,
        min_periods=min(rolling_window, ROLLING_MIN_PERIODS),
    ).median()
    local_mad = (abs_delta - local_median).abs().rolling(
        window=rolling_window,
        center=True,
        min_periods=min(rolling_window, ROLLING_MIN_PERIODS),
    ).median()
    denominator = local_mad * 1.4826
    local_z = (abs_delta - local_median).abs() / denominator

    quantile_threshold = float(abs_delta.dropna().quantile(change_quantile))
    abs_floor = METRIC_CONFIG[metric]["min_abs_delta"]
    effective_threshold = max(quantile_threshold, abs_floor)

    mask = (
        values.notna()
        & previous_values.notna()
        & denominator.gt(0)
        & local_z.ge(local_z_threshold)
        & abs_delta.ge(effective_threshold)
    )

    flagged = pd.DataFrame(
        {
            "datetime": metric_frame.loc[mask, "datetime"],
            "metric": metric,
            "irr_column": irr_column,
            "value": values.loc[mask],
            "previous_value": previous_values.loc[mask],
            "signed_delta": signed_delta.loc[mask],
            "abs_delta": abs_delta.loc[mask],
            "local_median_abs_delta": local_median.loc[mask],
            "local_mad_abs_delta": local_mad.loc[mask],
            "local_z": local_z.loc[mask],
            "change_threshold": effective_threshold,
            "change_quantile": change_quantile,
            "local_z_threshold": local_z_threshold,
        }
    ).reset_index(drop=True)

    return flagged, effective_threshold


def collapse_flagged_points_to_events(
    flagged_points: pd.DataFrame,
    metric: str,
    change_threshold: float,
    merge_gap_minutes: int,
    min_flagged_points: int,
    plot_context_hours: float,
) -> pd.DataFrame:
    """Merge nearby flagged timestamps into one irregularity event."""
    if flagged_points.empty:
        return pd.DataFrame(
            columns=[
                "event_id",
                "metric",
                "event_start",
                "event_end",
                "duration_minutes",
                "flagged_points",
                "peak_datetime",
                "peak_value",
                "peak_previous_value",
                "peak_signed_delta",
                "peak_abs_delta",
                "peak_local_z",
                "change_threshold",
                "merge_gap_minutes",
                "plot_context_hours",
                "plot_start",
                "plot_end",
                "rule",
            ]
        )

    flagged_points = flagged_points.sort_values("datetime").reset_index(drop=True)
    gap_breaks = flagged_points["datetime"].diff().gt(pd.Timedelta(minutes=merge_gap_minutes))
    event_group = gap_breaks.fillna(False).cumsum()
    plot_context = pd.Timedelta(hours=plot_context_hours)

    records: list[dict[str, object]] = []
    for _, group in flagged_points.groupby(event_group):
        if len(group) < min_flagged_points:
            continue

        peak_idx = group["abs_delta"].idxmax()
        peak_row = group.loc[peak_idx]
        event_start = pd.Timestamp(group["datetime"].min())
        event_end = pd.Timestamp(group["datetime"].max())
        duration_minutes = int((event_end - event_start) / pd.Timedelta(minutes=1)) + 1

        records.append(
            {
                "metric": metric,
                "event_start": event_start,
                "event_end": event_end,
                "duration_minutes": duration_minutes,
                "flagged_points": int(len(group)),
                "peak_datetime": pd.Timestamp(peak_row["datetime"]),
                "peak_value": float(peak_row["value"]),
                "peak_previous_value": float(peak_row["previous_value"]),
                "peak_signed_delta": float(peak_row["signed_delta"]),
                "peak_abs_delta": float(peak_row["abs_delta"]),
                "peak_local_z": float(peak_row["local_z"]),
                "change_threshold": float(change_threshold),
                "merge_gap_minutes": int(merge_gap_minutes),
                "plot_context_hours": float(plot_context_hours),
                "plot_start": event_start - plot_context,
                "plot_end": event_end + plot_context,
                "rule": "extreme_first_difference",
            }
        )

    if not records:
        return pd.DataFrame(
            columns=[
                "event_id",
                "metric",
                "event_start",
                "event_end",
                "duration_minutes",
                "flagged_points",
                "peak_datetime",
                "peak_value",
                "peak_previous_value",
                "peak_signed_delta",
                "peak_abs_delta",
                "peak_local_z",
                "change_threshold",
                "merge_gap_minutes",
                "plot_context_hours",
                "plot_start",
                "plot_end",
                "rule",
            ]
        )

    events = pd.DataFrame(records).sort_values(["event_start", "metric"]).reset_index(drop=True)
    return events[
        [
            "metric",
            "event_start",
            "event_end",
            "duration_minutes",
            "flagged_points",
            "peak_datetime",
            "peak_value",
            "peak_previous_value",
            "peak_signed_delta",
            "peak_abs_delta",
            "peak_local_z",
            "change_threshold",
            "merge_gap_minutes",
            "plot_context_hours",
            "plot_start",
            "plot_end",
            "rule",
        ]
    ]


def detect_first_difference_events(
    parquet_path: Path,
    change_quantile: float = DEFAULT_CHANGE_QUANTILE,
    local_z_threshold: float = DEFAULT_LOCAL_Z_THRESHOLD,
    rolling_window: int = DEFAULT_ROLLING_WINDOW,
    merge_gap_minutes: int = DEFAULT_MERGE_GAP_MINUTES,
    min_flagged_points: int = DEFAULT_MIN_FLAGGED_POINTS,
    plot_context_hours: float = DEFAULT_PLOT_CONTEXT_HOURS,
) -> pd.DataFrame:
    """Detect the legacy minute-to-minute first-difference events."""
    event_frames: list[pd.DataFrame] = []

    for metric in METRICS:
        metric_frame = load_metric_frame(parquet_path, metric)
        flagged_points, threshold = detect_metric_flagged_points(
            metric_frame,
            metric,
            change_quantile,
            local_z_threshold,
            rolling_window,
        )
        event_frames.append(
            collapse_flagged_points_to_events(
                flagged_points,
                metric,
                threshold,
                merge_gap_minutes,
                min_flagged_points,
                plot_context_hours,
            )
        )

    events = pd.concat(event_frames, ignore_index=True) if event_frames else pd.DataFrame()
    if events.empty:
        return events

    events = events.sort_values(["event_start", "metric"]).reset_index(drop=True)
    events["event_id"] = [
        f"{metric}_irr_event_{index:03d}"
        for metric, index in zip(events["metric"], range(1, len(events) + 1))
    ]
    events["plot_label"] = events["event_id"]
    return events


def detect_irregularity_events(
    parquet_path: Path,
    mode: str = DEFAULT_MODE,
    workbook_path: Path = COLUMN_MAP_WORKBOOK,
    daylight_min_irr: float = DEFAULT_DAYLIGHT_MIN_IRR,
    physical_max_irr: float = DEFAULT_PHYSICAL_MAX_IRR,
    segment_closure_break_threshold: float = DEFAULT_SEGMENT_CLOSURE_BREAK_THRESHOLD,
    segment_closure_collapse_threshold: float = DEFAULT_SEGMENT_CLOSURE_COLLAPSE_THRESHOLD,
    daily_merge_gap_days: int = DEFAULT_DAILY_MERGE_GAP_DAYS,
    daily_min_event_days: int = DEFAULT_DAILY_MIN_EVENT_DAYS,
    single_day_severe_score: float = DEFAULT_SINGLE_DAY_SEVERE_SCORE,
    plot_context_days: float = DEFAULT_PLOT_CONTEXT_DAYS,
    change_quantile: float = DEFAULT_CHANGE_QUANTILE,
    local_z_threshold: float = DEFAULT_LOCAL_Z_THRESHOLD,
    rolling_window: int = DEFAULT_ROLLING_WINDOW,
    merge_gap_minutes: int = DEFAULT_MERGE_GAP_MINUTES,
    min_flagged_points: int = DEFAULT_MIN_FLAGGED_POINTS,
    plot_context_hours: float = DEFAULT_PLOT_CONTEXT_HOURS,
) -> pd.DataFrame:
    """Detect irradiance irregularity events using the requested mode."""
    if mode == "first_difference":
        return detect_first_difference_events(
            parquet_path,
            change_quantile=change_quantile,
            local_z_threshold=local_z_threshold,
            rolling_window=rolling_window,
            merge_gap_minutes=merge_gap_minutes,
            min_flagged_points=min_flagged_points,
            plot_context_hours=plot_context_hours,
        )

    return detect_mapping_window_events(
        parquet_path,
        workbook_path=workbook_path,
        daylight_min_irr=daylight_min_irr,
        physical_max_irr=physical_max_irr,
        segment_closure_break_threshold=segment_closure_break_threshold,
        segment_closure_collapse_threshold=segment_closure_collapse_threshold,
        daily_merge_gap_days=daily_merge_gap_days,
        daily_min_event_days=daily_min_event_days,
        single_day_severe_score=single_day_severe_score,
        plot_context_days=plot_context_days,
    )


def write_events_csv(events_output: Path, events: pd.DataFrame) -> None:
    """Write the irregularity events CSV."""
    events_output.parent.mkdir(parents=True, exist_ok=True)
    events.to_csv(events_output, index=False)


def empty_plot_index_frame() -> pd.DataFrame:
    """Return an empty plot-index frame with the expected schema."""
    return pd.DataFrame(
        columns=[
            "plot_label",
            "event_id",
            "plot_metric",
            "plot_filename",
            "plot_path",
            "irregularity_start",
            "irregularity_end",
            "source",
            "rule",
            "rows_plotted",
        ]
    )


def write_plot_index_csv(plot_index_output: Path, plot_index: pd.DataFrame) -> None:
    """Write the plot-index CSV used to match files to irregularity windows."""
    plot_index_output.parent.mkdir(parents=True, exist_ok=True)
    plot_index.to_csv(plot_index_output, index=False)


def export_first_difference_event_plots(
    parquet_path: Path,
    events: pd.DataFrame,
    output_dir: Path,
    context_hours_override: float | None = None,
    dpi: int = 150,
) -> pd.DataFrame:
    """Export one contextual PNG per legacy first-difference event."""
    if events.empty:
        return empty_plot_index_frame()

    output_dir.mkdir(parents=True, exist_ok=True)
    metric_frames = {
        metric: load_metric_frame(parquet_path, metric)
        for metric in sorted(events["metric"].unique())
    }
    results: list[dict[str, object]] = []

    for event in events.itertuples(index=False):
        metric_frame = metric_frames[event.metric]
        irr_column = f"{event.metric}_Irr"
        context_hours = context_hours_override if context_hours_override is not None else event.plot_context_hours
        context = pd.Timedelta(hours=context_hours)
        plot_start = pd.Timestamp(event.event_start) - context
        plot_end = pd.Timestamp(event.event_end) + context
        window = metric_frame.loc[
            (metric_frame["datetime"] >= plot_start) & (metric_frame["datetime"] <= plot_end),
            ["datetime", irr_column],
        ].copy()
        if window.empty:
            continue

        metric_dir = output_dir / event.metric.lower()
        metric_dir.mkdir(parents=True, exist_ok=True)
        output_path = metric_dir / f"{event.event_id}.png"

        fig, ax = plt.subplots(figsize=(14, 6))
        ax.plot(
            window["datetime"],
            window[irr_column],
            color=METRIC_CONFIG[event.metric]["color"],
            linewidth=0.8,
        )
        ax.axvspan(pd.Timestamp(event.event_start), pd.Timestamp(event.event_end), color="#d62728", alpha=0.18)
        ax.axvline(pd.Timestamp(event.peak_datetime), color="#d62728", linestyle="--", linewidth=1)
        ax.set_title(
            f"{event.event_id} | {event.metric} IRR irregularity\n"
            f"{pd.Timestamp(event.event_start)} to {pd.Timestamp(event.event_end)} | "
            f"peak Δ={event.peak_abs_delta:.1f}"
        )
        ax.set_xlabel("Datetime")
        ax.set_ylabel("IRR")
        ax.grid(alpha=0.25, linewidth=0.6)
        ax.margins(x=0)
        locator = mdates.AutoDateLocator()
        ax.xaxis.set_major_locator(locator)
        ax.xaxis.set_major_formatter(mdates.ConciseDateFormatter(locator))
        ax.spines["top"].set_visible(False)
        ax.spines["right"].set_visible(False)
        fig.tight_layout()
        fig.savefig(output_path, dpi=dpi, bbox_inches="tight")
        plt.close(fig)

        results.append(
            {
                "plot_label": getattr(event, "plot_label", event.event_id),
                "event_id": event.event_id,
                "plot_metric": event.metric,
                "plot_filename": output_path.name,
                "plot_path": output_path,
                "irregularity_start": pd.Timestamp(event.event_start),
                "irregularity_end": pd.Timestamp(event.event_end),
                "source": "first_difference",
                "rule": event.rule,
                "rows_plotted": len(window),
            }
        )

    return pd.DataFrame(results)


def export_mapping_window_event_plots(
    parquet_path: Path,
    events: pd.DataFrame,
    output_dir: Path,
    context_days_override: float | None = None,
    dpi: int = 150,
) -> pd.DataFrame:
    """Export one raw-IRR contextual PNG per mapping-window event."""
    if events.empty:
        return empty_plot_index_frame()

    output_dir.mkdir(parents=True, exist_ok=True)
    metric_frames = {metric: load_metric_frame(parquet_path, metric) for metric in METRICS}

    results: list[dict[str, object]] = []
    for event in events.itertuples(index=False):
        context_days = context_days_override if context_days_override is not None else float(event.plot_context_days)
        plot_start = pd.Timestamp(event.event_start) - pd.Timedelta(days=context_days)
        plot_end = pd.Timestamp(event.event_end) + pd.Timedelta(days=context_days)

        metrics_text = str(getattr(event, "affected_metrics", "") or "")
        metrics_to_write = [metric for metric in metrics_text.split(",") if metric in METRICS] or list(METRICS)
        event_start = pd.Timestamp(event.event_start)
        event_end = pd.Timestamp(event.event_end)

        for focus_metric in metrics_to_write:
            metric_frame = metric_frames[focus_metric]
            irr_column = f"{focus_metric}_Irr"
            window = metric_frame.loc[
                (metric_frame["datetime"] >= plot_start) & (metric_frame["datetime"] <= plot_end),
                ["datetime", irr_column],
            ].copy()
            if window.empty:
                continue

            metric_dir = output_dir / focus_metric.lower()
            metric_dir.mkdir(parents=True, exist_ok=True)
            output_path = metric_dir / f"{event.event_id}.png"

            fig, ax = plt.subplots(figsize=(15, 6))
            ax.plot(
                window["datetime"],
                window[irr_column],
                color=METRIC_CONFIG[focus_metric]["color"],
                linewidth=0.8,
            )
            ax.axvspan(event_start, event_end, color="#d62728", alpha=0.16)
            ax.set_title(
                f"{event.event_id} | {focus_metric} IRR\n"
                f"{event_start.date()} to {event_end.date()}"
            )
            ax.set_ylabel("IRR")
            ax.set_xlabel("Datetime")
            ax.grid(alpha=0.25, linewidth=0.6)
            locator = mdates.AutoDateLocator()
            ax.xaxis.set_major_locator(locator)
            ax.xaxis.set_major_formatter(mdates.ConciseDateFormatter(locator))
            ax.margins(x=0)
            ax.spines["top"].set_visible(False)
            ax.spines["right"].set_visible(False)
            fig.tight_layout()
            fig.savefig(output_path, dpi=dpi, bbox_inches="tight")
            plt.close(fig)

            results.append(
                {
                    "plot_label": getattr(event, "plot_label", event.event_id),
                    "event_id": event.event_id,
                    "plot_metric": focus_metric,
                    "plot_filename": output_path.name,
                    "plot_path": output_path,
                    "irregularity_start": pd.Timestamp(event.event_start),
                    "irregularity_end": pd.Timestamp(event.event_end),
                    "source": getattr(event, "source", "mapping_window"),
                    "rule": event.rule,
                    "rows_plotted": len(window),
                }
            )

    return pd.DataFrame(results)


def export_event_plots(
    parquet_path: Path,
    events: pd.DataFrame,
    output_dir: Path,
    context_hours_override: float | None = None,
    plot_index_output: Path | None = DEFAULT_PLOT_INDEX_OUTPUT,
    dpi: int = 150,
) -> pd.DataFrame:
    """Export contextual plots for either event schema."""
    if "source" in events.columns:
        plot_results = export_mapping_window_event_plots(
            parquet_path,
            events,
            output_dir,
            context_days_override=context_hours_override,
            dpi=dpi,
        )
    else:
        plot_results = export_first_difference_event_plots(
            parquet_path,
            events,
            output_dir,
            context_hours_override=context_hours_override,
            dpi=dpi,
        )

    if plot_index_output is not None:
        write_plot_index_csv(plot_index_output, plot_results if not plot_results.empty else empty_plot_index_frame())
    return plot_results


def main() -> None:
    """Detect irregularity events and write the events CSV."""
    args = parse_args()
    events = detect_irregularity_events(
        args.input_parquet,
        mode=args.mode,
        workbook_path=args.workbook,
        daylight_min_irr=args.daylight_min_irr,
        physical_max_irr=args.physical_max_irr,
        segment_closure_break_threshold=args.segment_closure_break_threshold,
        segment_closure_collapse_threshold=args.segment_closure_collapse_threshold,
        daily_merge_gap_days=args.daily_merge_gap_days,
        daily_min_event_days=args.daily_min_event_days,
        single_day_severe_score=args.single_day_severe_score,
        plot_context_days=args.plot_context_days,
        change_quantile=args.change_quantile,
        local_z_threshold=args.local_z_threshold,
        rolling_window=args.rolling_window,
        merge_gap_minutes=args.merge_gap_minutes,
        min_flagged_points=args.min_flagged_points,
        plot_context_hours=args.plot_context_hours,
    )
    write_events_csv(args.events_output, events)

    print(
        f"Wrote {len(events)} IRR irregularity events to {args.events_output} from {args.input_parquet} "
        f"using mode={args.mode}.",
        flush=True,
    )
    if not events.empty:
        group_column = "rule" if "rule" in events.columns else "metric"
        print(events.groupby(group_column).size().to_string(), flush=True)


if __name__ == "__main__":
    main()
